require('dotenv').config()
const express = require('express')
const app = express()
const PORT = process.env.PORT || 8081
const cookieParser = require('cookie-parser')
const cors = require('cors')
const connectDB = require('./config/dbConn')

connectDB()
app.use(cors({credentials: true, origin: true}))
app.use(express.json())
app.use(cookieParser())
app.use('/auth', require('./routes/authRoutes'))
app.use('/users', require('./routes/userRoutes'))
app.use('/games', require('./routes/gameRoutes'))
app.use('/admin', require('./routes/adminRoutes'))
app.listen(PORT, () => console.log(`Server running on port ${PORT}`))