###

POST http://localhost:8081/users/register
Content-Type: application/json

{
    "username": "rkanoff2",
    "email": "rkanoff2@email.com",
    "password": "password"
}

###

POST http://localhost:8081/auth/login
Content-Type: application/json

{
    "username": "rkanoff1",
    "password": "password"
}

###

GET http://localhost:8081/auth/refresh
Content-Type: application/json

###

POST http://localhost:8081/auth/logout
Content-Type: application/json

###

POST http://localhost:8081/games/create
Content-Type: application/json

{
    "name": "TestGame1",
    "type": "Justwhatevs",
    "numPlayers": 2,
    "players": ["player1"]
}

###

GET http://localhost:8081/games/getAll
Content-Type: application/json

###

POST http://localhost:8081/admin/createAdmin
Content-Type: application/json

{
    "userId": "63b78864852ad3ed08912890",
    "key": "0ba7ac6d7594116e279d6254d5897c10"
}

###

POST http://localhost:8081/admin/removeGame
Content-Type: application/json

{
    "gameId": "63b633b093fa76cfd9b53689"
}

###